repos:
  # Lint + formatador ultra-rápido
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: ["--fix", "--exit-zero"]
      - id: ruff-format
        args: ["--exit-zero"]

  # Segurança de código
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-lll", "-r", "."]

  # Hook local para garantir __init__.py em todas as pastas
  - repo: local
    hooks:
      - id: ensure-init-files
        name: Ensure __init__.py in all dirs
        entry: bash -c 'find . -type d \( -path "./.*" -o -path "./.venv*" \) -prune -o -type d -exec sh -c "[ -f \"$0/__init__.py\" ] || touch \"$0/__init__.py\"" {} \;'
        language: system
        pass_filenames: false
