name: CI & Auto-PR to Develop

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-cov bandit safety

      - name: Run pre-commit hooks
        run: pre-commit run --all-files || true

      - name: Run security checks
        run: |
          bandit -r .
          safety check || true

      - name: Run tests with coverage
        run: pytest --cov=./ --cov-report=term

      - name: Create PR to develop
        if: github.event_name == 'push'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto-PR: ${{ github.ref_name }} → develop'
          pr_body: 'This PR was automatically created by the ci-feature-develop workflow.'
          labels: 'feature, auto-pr'
