name: CI & Auto-PR develop → main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # (mesmos passos de CI)
      - name: Create PR to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: develop
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto-PR: develop → main'
          pr_body: 'Auto-PR gerado por push em develop.'
          labels: 'auto-pr'
