name: CI feature → develop

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install lint/security deps
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit bandit safety

      - name: Run pre-commit
        run: pre-commit run --all-files || true

      - name: Security checks (não-bloqueante)
        run: |
          bandit -r . --exit-zero
          safety check || true

  tests:
    runs-on: ubuntu-latest
    needs: lint-security
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=./ --cov-report=term

  create-pr-develop:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto-PR: ${{ github.ref_name }} → develop'
          pr_body: 'Gerado automaticamente pelo workflow CI feature → develop.'
          labels: 'feature, auto-pr'
