name: CI feature → develop

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install ruff bandit
      - run: ruff check . --fix --exit-zero
      - run: bandit -r . --exit-zero
      - run: pip install -r requirements-dev.txt
      - run: pytest --cov=./ --cov-report=term

  create-pr-develop:
    needs: lint-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          pr_title: 'Auto-PR: ${{ github.ref_name }} → develop'
          pr_body: 'Gerado automaticamente após push em feature.'
          pr_label: 'feature,auto-pr'
