name: CI develop → master

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    if: contains(github.event.head_commit.message, 'Merge pull request') || contains(github.event.head_commit.message, '(#')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Prepare test environment
        run: |
          find . -type d \( -path "./.*" -o -path "./.venv*" \) \
            -prune -o -type d \
            -exec sh -c '[ -f "$0/__init__.py" ] || touch "$0/__init__.py"' {} \;
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
      - run: pytest --cov=./ --cov-report=term

  create-pr-master:
    if: contains(github.event.head_commit.message, 'Merge pull request') || contains(github.event.head_commit.message, '(#')
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: develop
          destination_branch: master
          github_token: ${{ secrets.REPO_SYNC_TOKEN }} # PAT
          pr_title: 'PR para revisão: develop → master'
          pr_body: 'Gerado automaticamente após merge em develop.'
          pr_label: 'release-candidate,review'