name: CI release → master

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-master-pr:
    if: contains(github.event.head_commit.message, 'Merge pull request') || contains(github.event.head_commit.message, '(#')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: master
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          pr_title: '[release] ${{ github.ref_name }}'
          pr_body: 'Atualiza master a partir da ${{ github.ref_name }} e prepara publicação no PyPI.'
          pr_label: 'release,auto-pr'
