name: Criar Release e Abrir PR para master

on:
  push:
    branches:
      - master   # dispara ao merge de develop → master

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt ruff bandit
      - run: ruff check . --fix --exit-zero
      - run: bandit -r . --exit-zero
      - name: Prepare test environment
        run: |
          find . -type d \( -path "./.*" -o -path "./.venv*" \) \
            -prune -o -type d \
            -exec sh -c '[ -f "$0/__init__.py" ] || touch "$0/__init__.py"' {} \;
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
      - run: pytest --cov=./ --cov-report=term

  create-release-pr:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Determinar próxima tag e atualizar versão
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          BASE="${LAST_TAG#v}"
          MAJOR=$(echo $BASE | cut -d. -f1)
          MINOR=$(echo $BASE | cut -d. -f2)
          PATCH=$(echo $BASE | cut -d. -f3)
          PATCH=$((PATCH+1))
          NEXT_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "Nova tag: $NEXT_TAG"
          python - <<EOF
          import toml
          data = toml.load("pyproject.toml")
          data["project"]["version"] = "${NEXT_TAG#v}"
          with open("pyproject.toml", "w") as f:
              toml.dump(data, f)
          EOF

          echo "next_tag=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Criar branch e PR de release
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/${{ steps.version.outputs.next_tag }}
          destination_branch: master
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          pr_title: '[release] ${{ steps.version.outputs.next_tag }}'
          pr_body: 'Atualiza versão para ${{ steps.version.outputs.next_tag }} e prepara publicação no PyPI.'
          pr_label: 'release,auto-pr'
