name: Publicar no PyPI após Merge de release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    if: contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      - name: Ler versão do pyproject.toml e criar tag
        id: version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "Versão lida: $VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build & Upload para PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.CI }}
        run: |
          python -m build
          python -m twine upload dist/*
