name: Publicar no PyPI após Merge de release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    if: contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt build twine
      - name: Build & Upload para PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.CI }}
        run: |
          python -m build
          python -m twine upload dist/*
